name: Fetch Liverpool fixtures

permissions:
  contents: write
  
on:
  schedule:
    - cron: "0 4 * * *"   # once per day at 04:00 UTC
  workflow_dispatch: {}     # (optional) allows you to trigger manually from the Actions tab

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Run fetcher
        env:
          X_APISPORTS_KEY: ${{ secrets.X_APISPORTS_KEY }}
          TEAM_ID: "40" 
          DATE_FROM: "2025-09-01"
          DATE_TO:   "2026-04-15"
        run: python scripts/fetch_fixtures.py

      - name: Commit updated JSON
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/fixtures.json
            git commit -m "chore: daily update fixtures.json"
            git push
          else
            echo "No changes today."
          fi
